<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_New project_avatar avatar-small circle</name>
   <tag></tag>
   <elementGuidId>a914ea36-5df4-416d-a511-cee6f32ebba8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.avatar.avatar-small.circle</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//img[@alt='@ihsankjamil'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>1baf8684-a2e3-4986-8a6f-b2959f161027</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://avatars.githubusercontent.com/u/36791858?s=40&amp;v=4</value>
      <webElementGuid>95faf33b-519f-497b-8250-47369d80513e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>@ihsankjamil</value>
      <webElementGuid>7e4301b9-6d41-4b10-8183-9ce28b6e445c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>2d430f78-752b-4fcf-b99c-6d30f58a8c35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>5c1581bc-e349-4091-a4cd-0b7a23be090c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>efe87aa1-911d-41c6-b9f8-72963f1d4b67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-view-component</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>9ceba8f3-083c-4821-9ac7-5948473c840b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>avatar avatar-small circle</value>
      <webElementGuid>c6500eb3-c908-4901-8f68-817f7c7335ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;logged-in env-production page-responsive full-width intent-mouse&quot;]/div[@class=&quot;position-relative js-header-wrapper&quot;]/header[@class=&quot;Header js-details-container Details px-3 px-md-4 px-lg-5 flex-wrap flex-md-nowrap&quot;]/div[@class=&quot;Header-item position-relative mr-0 d-none d-md-flex&quot;]/details[@class=&quot;details-overlay details-reset js-feature-preview-indicator-container&quot;]/summary[@class=&quot;Header-link&quot;]/img[@class=&quot;avatar avatar-small circle&quot;]</value>
      <webElementGuid>f3ad330b-a679-4f18-bfcb-adae52749060</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='@ihsankjamil'])[2]</value>
      <webElementGuid>39de8bb5-7089-42e8-94df-3028cb23fc8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//summary/img</value>
      <webElementGuid>5b72fd28-06f8-4df9-a091-7f895cd3cc39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://avatars.githubusercontent.com/u/36791858?s=40&amp;v=4' and @alt = '@ihsankjamil']</value>
      <webElementGuid>4f317dad-f041-4017-857e-159ed1f0b948</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
