<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Sign In</name>
   <tag></tag>
   <elementGuidId>03267a72-9c11-413c-bc63-366ec3aaa8c1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='submit']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.btn.login-button.btn-submit.btn-small</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c3d5132c-1c68-4760-881a-5c67a1d452b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn login-button btn-submit btn-small</value>
      <webElementGuid>85f8ce51-ca28-499a-9aa4-adb5a49acd15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>d7170b8a-4675-4ab1-bc9c-27c9639cf616</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>57db4568-deec-43d9-aa11-5ecb783f5a7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>359d25fa-390b-46b1-9b96-b14fcba34485</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-uia</name>
      <type>Main</type>
      <value>login-submit-button</value>
      <webElementGuid>7e0be1ed-8e35-4b3b-9ba4-9ab842c96011</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sign In</value>
      <webElementGuid>f0cb602f-5c24-42e4-af20-d9c9a8b4ac3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;appMountPoint&quot;)/div[@class=&quot;login-wrapper hybrid-login-wrapper&quot;]/div[@class=&quot;login-body&quot;]/div[1]/div[@class=&quot;login-content login-form hybrid-login-form hybrid-login-form-signup&quot;]/div[@class=&quot;hybrid-login-form-main&quot;]/form[@class=&quot;login-form&quot;]/button[@class=&quot;btn login-button btn-submit btn-small&quot;]</value>
      <webElementGuid>02d67db4-c876-401f-953a-cec728b033e8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='submit']</value>
      <webElementGuid>e40fd9cb-b28a-4656-a4f4-79924f1d1837</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='appMountPoint']/div/div[3]/div/div/div/form/button</value>
      <webElementGuid>51f4bf8b-5da7-43f5-b468-fdba6a3a3e2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SHOW'])[1]/following::button[1]</value>
      <webElementGuid>3d3c4516-c14f-4025-8587-ea619eba12cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Password'])[1]/following::button[2]</value>
      <webElementGuid>669bde0b-8f11-4cea-80ac-cee56d882288</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Remember me'])[1]/preceding::button[1]</value>
      <webElementGuid>e1ff2a93-0ea8-4e3c-9314-47d8e19d1d11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Need help?'])[1]/preceding::button[1]</value>
      <webElementGuid>73254b3c-f23e-4b89-87c7-c3df710ae572</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/button</value>
      <webElementGuid>f4275c6b-58d7-433b-acb6-bb3b48b77c88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and (text() = 'Sign In' or . = 'Sign In')]</value>
      <webElementGuid>e4877b39-8489-4f7d-9986-43849c3ba7c0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
