<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Ibnu_profile-icon</name>
   <tag></tag>
   <elementGuidId>ba1d0c80-8adb-42c6-aa9f-7b1cbda98300</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='appMountPoint']/div/div/div/div/div[2]/div/div/ul/li[4]/div/a/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>e685eaf3-5009-4b2a-b7b0-8874c474f568</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>profile-icon</value>
      <webElementGuid>152501bb-7bc8-42f4-92c2-423c3ae3dd2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-profile-guid</name>
      <type>Main</type>
      <value>BZN23UYZFVBQXOXUVO7ZAWPKXA</value>
      <webElementGuid>5c46fa00-8a6e-4d63-b6ed-b66de2fd44e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;appMountPoint&quot;)/div[@class=&quot;netflix-sans-font-loaded&quot;]/div[1]/div[1]/div[@class=&quot;bd dark-background&quot;]/div[@class=&quot;profiles-gate-container&quot;]/div[@class=&quot;centered-div list-profiles-container&quot;]/div[@class=&quot;list-profiles&quot;]/ul[@class=&quot;choose-profile&quot;]/li[@class=&quot;profile&quot;]/div[1]/a[@class=&quot;profile-link&quot;]/div[@class=&quot;avatar-wrapper&quot;]/div[@class=&quot;profile-icon&quot;]</value>
      <webElementGuid>64c7979d-3626-494c-8b27-4216214085d9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='appMountPoint']/div/div/div/div/div[2]/div/div/ul/li[4]/div/a/div/div</value>
      <webElementGuid>b64cb4ad-0efb-485b-95b7-45b5b8c44f28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ibnu'])[1]/following::div[4]</value>
      <webElementGuid>40a1ec9b-1a7f-4d15-b838-26b8823dc3ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Robert'])[1]/following::div[8]</value>
      <webElementGuid>b404fd77-0c51-415a-a2ef-3447dc900c2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jamil'])[1]/preceding::div[1]</value>
      <webElementGuid>875d1b0b-9380-43f4-a9e5-1326080c6fab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Arfan'])[1]/preceding::div[4]</value>
      <webElementGuid>50d72343-13cf-4a36-a491-5798c24828da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/div/a/div/div</value>
      <webElementGuid>48232019-386a-47c3-acd3-68b261ed1904</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
