<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Sign In_userLoginId</name>
   <tag></tag>
   <elementGuidId>b41a098c-8561-4ed3-9c7e-82e8cd74df03</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='id_userLoginId']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#id_userLoginId</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bfe9ad2c-a06d-4c1c-9f75-94ce61016574</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c989fc67-2349-43dd-acd5-d992e5caa9d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-uia</name>
      <type>Main</type>
      <value>login-field</value>
      <webElementGuid>e044e341-065e-4423-96ac-33ec02e353ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>userLoginId</value>
      <webElementGuid>562293a8-5456-4f5c-8cb0-a368ddd9c188</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nfTextField error</value>
      <webElementGuid>139abb96-2259-4bc1-943f-f20f2170427d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>id_userLoginId</value>
      <webElementGuid>80d08209-3f31-4c28-9eef-7da75d62e3d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>8d0316a8-bbb5-42eb-8a02-96790a435f8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>e36f5c34-7ad7-461e-937f-f69ae5e260d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;id_userLoginId&quot;)</value>
      <webElementGuid>5cf7e5df-5d14-468c-9c13-8672de0cab7a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='id_userLoginId']</value>
      <webElementGuid>dd38a6e9-5848-4341-b479-9887aa0ad36e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='appMountPoint']/div/div[3]/div/div/div/form/div/div/div/label/input</value>
      <webElementGuid>36386804-e86c-4c31-a9ea-8e9c89f88edd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>885cb0ac-979b-450b-bb61-9215a45b6b59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'userLoginId' and @id = 'id_userLoginId']</value>
      <webElementGuid>29d05769-c002-4ba7-b2fb-9f3111be3cda</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
