<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Search__6q-tv</name>
   <tag></tag>
   <elementGuidId>d2825531-9788-496f-9208-2ffae2a63939</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='react-root']/section/nav/div[2]/div/div/div[3]/div/div[6]/div/span/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span._2dbep.qNELH > img._6q-tv</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>cb64bcb1-df3f-4d30-b1e8-91163c5f7d6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>ihsankjamil's profile picture</value>
      <webElementGuid>6d5083e5-8caf-4041-9d0b-8e350da56309</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_6q-tv</value>
      <webElementGuid>c522b99e-6d4d-48c1-8e6a-d733c03dcaf9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>crossorigin</name>
      <type>Main</type>
      <value>anonymous</value>
      <webElementGuid>d4a9c91c-1e32-44d7-886d-84f5b0e288db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>user-avatar</value>
      <webElementGuid>7eae5c79-1891-4c52-b0c0-5ef4911f61dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>draggable</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>6ff69484-d0f4-4d15-8d1d-ef1bfa6bb979</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://instagram.fbdo9-1.fna.fbcdn.net/v/t51.2885-19/275514405_4828259497221879_3874580216732411935_n.jpg?stp=dst-jpg_s150x150&amp;_nc_ht=instagram.fbdo9-1.fna.fbcdn.net&amp;_nc_cat=103&amp;_nc_ohc=sGcZcZlMIRYAX9dO1cH&amp;edm=AIQHJ4wBAAAA&amp;ccb=7-4&amp;oh=00_AT_KHhbl9rY1iQPPpBgn5F_tmk_YgK0Y0kLaV18nsA1QDg&amp;oe=628A8744&amp;_nc_sid=7b02f1</value>
      <webElementGuid>898a3e8e-d052-465e-a9e6-39346687f671</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;react-root&quot;)/section[@class=&quot;_9eogI E3X2T&quot;]/nav[@class=&quot;kqZqN x-Vyw&quot;]/div[@class=&quot;_8MQSO  Cx7Bp&quot;]/div[@class=&quot;_lz6s&quot;]/div[@class=&quot;MWDvN&quot;]/div[@class=&quot;ctQZg KtFt3&quot;]/div[@class=&quot;J5g42&quot;]/div[@class=&quot;XrOey&quot;]/div[@class=&quot;EforU&quot;]/span[@class=&quot;_2dbep qNELH&quot;]/img[@class=&quot;_6q-tv&quot;]</value>
      <webElementGuid>a15930e5-9659-46e2-ad63-6a82032b2010</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='react-root']/section/nav/div[2]/div/div/div[3]/div/div[6]/div/span/img</value>
      <webElementGuid>d26a021c-b2f1-438d-8b4a-2ac10c9af5a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt=&quot;ihsankjamil's profile picture&quot;]</value>
      <webElementGuid>3e9f2937-b38e-46f4-9a69-88f5dee1e427</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/span/img</value>
      <webElementGuid>e89e213b-608b-40bc-8d1c-dfe21fb2bdbc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = concat(&quot;ihsankjamil&quot; , &quot;'&quot; , &quot;s profile picture&quot;) and @src = 'https://instagram.fbdo9-1.fna.fbcdn.net/v/t51.2885-19/275514405_4828259497221879_3874580216732411935_n.jpg?stp=dst-jpg_s150x150&amp;_nc_ht=instagram.fbdo9-1.fna.fbcdn.net&amp;_nc_cat=103&amp;_nc_ohc=sGcZcZlMIRYAX9dO1cH&amp;edm=AIQHJ4wBAAAA&amp;ccb=7-4&amp;oh=00_AT_KHhbl9rY1iQPPpBgn5F_tmk_YgK0Y0kLaV18nsA1QDg&amp;oe=628A8744&amp;_nc_sid=7b02f1']</value>
      <webElementGuid>3e769f32-e47f-4383-9e30-4020307ba48d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
