<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div__hOWUEV7wHgfYPPLcnNXt</name>
   <tag></tag>
   <elementGuidId>6dacc47a-1820-4683-9515-fbea2cba7177</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='main']/div/div[2]/div/header/button/figure/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.hOWUEV7wHgfYPPLcnNXt</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>0e13901d-011d-4d7c-8a4c-9a1afdb33642</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hOWUEV7wHgfYPPLcnNXt</value>
      <webElementGuid>4a3e9155-3dcd-4ce1-8106-a63d48c06a7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>placeholder-wrapper</value>
      <webElementGuid>ce57d7b8-9cbd-43ee-a13b-8444711182c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/div[@class=&quot;Root encore-dark-theme&quot;]/div[@class=&quot;Root__top-container&quot;]/div[@class=&quot;Root__top-bar&quot;]/header[@class=&quot;facDIsOQo9q7kiWc4jSg&quot;]/button[@class=&quot;odcjv30UQnjaTv4sylc0&quot;]/figure[@class=&quot;jcZTHauCznHxn1lbigHS&quot;]/div[1]/div[@class=&quot;hOWUEV7wHgfYPPLcnNXt&quot;]</value>
      <webElementGuid>74dbc486-adfb-4f15-bef2-79caf1ab8c9b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main']/div/div[2]/div/header/button/figure/div/div</value>
      <webElementGuid>4680520f-c755-496b-91a3-ff956f28d8d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='`'])[2]/following::div[14]</value>
      <webElementGuid>9b405d0a-34d9-469c-994c-bf9f12b2913b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alt'])[2]/following::div[14]</value>
      <webElementGuid>84810751-bc29-45cc-8ce7-d29661daae70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ihsankjamil'])[1]/preceding::div[2]</value>
      <webElementGuid>097ad5c3-5a3e-43ae-8616-3607b42e9a2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Home'])[1]/preceding::div[4]</value>
      <webElementGuid>b6ac17e5-05d1-4eea-a454-f164a1519783</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//figure/div/div</value>
      <webElementGuid>b92731eb-4b7f-47aa-89d1-aa660c350224</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
