<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Skip</name>
   <tag></tag>
   <elementGuidId>d92e5188-a2dc-46c6-b8a3-e6377b679268</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='recaptcha-verify-button']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#recaptcha-verify-button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>70a21d14-1c04-4d95-a3cd-7eda5a20ab06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rc-button-default goog-inline-block</value>
      <webElementGuid>d8a37959-052b-4d31-a46d-a53cc42f5d56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>recaptcha-verify-button</value>
      <webElementGuid>8da21c6c-aebe-4db4-a8c9-9bbc014bc878</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>2653715b-1eb1-45e8-aa4a-bdb48becdc6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Skip</value>
      <webElementGuid>5189f13f-6072-44aa-95e0-ca9c5de9e544</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;recaptcha-verify-button&quot;)</value>
      <webElementGuid>63bb65aa-2f41-43b5-a820-5b8a31708f34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/latihanmedium/Page_Medium  Where good ideas find you/iframe_All sign up options_c-e9azcz7c8q1d</value>
      <webElementGuid>b5fbfb9f-08dd-4143-ad8b-936c2428aa8f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='recaptcha-verify-button']</value>
      <webElementGuid>5b915f70-898e-4765-9441-b13ac64d2f1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rc-imageselect']/div[3]/div[2]/div/div[2]/button</value>
      <webElementGuid>9a6971e3-bb1f-496d-a069-f020f0170dc3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='traffic lights'])[1]/following::button[6]</value>
      <webElementGuid>b7c5f03e-d80b-49b0-b18e-f624814b435b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'recaptcha-verify-button', '&quot;', ')')])[1]/preceding::button[1]</value>
      <webElementGuid>8bb506c4-4078-419e-bf38-5bd9a4a058b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Skip']/parent::*</value>
      <webElementGuid>968c7bc1-3d34-4bce-97a1-a48f3423141f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button</value>
      <webElementGuid>b6a3ae0a-6f61-4ca9-995d-89992a47abd7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'recaptcha-verify-button' and (text() = 'Skip' or . = 'Skip')]</value>
      <webElementGuid>02a6b08a-378e-4dc6-a7c6-0c8cfff678eb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
