<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_All sign up options_c-e9azcz7c8q1d</name>
   <tag></tag>
   <elementGuidId>754f0324-4484-401c-80d3-0c86ae88b375</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@name='c-e9azcz7c8q1d']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>iframe[name=&quot;c-e9azcz7c8q1d&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>4d561b0b-abc8-4ac0-a1a3-32154e3a611b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>recaptcha challenge expires in two minutes</value>
      <webElementGuid>59fc6b34-3ae7-4078-8bb8-6cc7f33ba10d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/bframe?hl=en&amp;v=M-QqaF9xk6BpjLH22uHZRhXt&amp;k=6Lfc37IUAAAAAKGGtC6rLS13R1Hrw_BqADfS1LRk</value>
      <webElementGuid>2fb5c27e-32b1-4873-b774-70307a29bdc7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>c-e9azcz7c8q1d</value>
      <webElementGuid>f8daf41f-4683-41e5-9969-6d997361c36d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>75626f80-3b56-44bc-84e2-423fb790c833</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>4fa0429a-46b8-4108-9be2-0259bd19b3a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sandbox</name>
      <type>Main</type>
      <value>allow-forms allow-popups allow-same-origin allow-scripts allow-top-navigation allow-modals allow-popups-to-escape-sandbox</value>
      <webElementGuid>8a4f62d8-0ac2-42a3-a042-a72b1a72b92d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[4]/div[2]/iframe[1]</value>
      <webElementGuid>9a81154f-183b-4102-9054-25b0bdb5fa1c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@name='c-e9azcz7c8q1d']</value>
      <webElementGuid>e350851e-463a-4220-b29c-65c082478564</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/iframe</value>
      <webElementGuid>8d4e22a3-cae4-4ae1-8fc0-4ea9964b7f13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@title = 'recaptcha challenge expires in two minutes' and @src = 'https://www.google.com/recaptcha/api2/bframe?hl=en&amp;v=M-QqaF9xk6BpjLH22uHZRhXt&amp;k=6Lfc37IUAAAAAKGGtC6rLS13R1Hrw_BqADfS1LRk' and @name = 'c-e9azcz7c8q1d']</value>
      <webElementGuid>a018d393-6ffa-4d8d-b047-895d11f35dc6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
