<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Your email_ou ov ow ox oy oz pa pb pc_b45929</name>
   <tag></tag>
   <elementGuidId>23e757d8-8020-4da5-92d1-6319acfae109</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.ou.ov.ow.ox.oy.oz.pa.pb.pc.pd.pe.pf.pg.ph.pi.nk.by.pj</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8b3e56e8-95f7-491c-906e-911de7b54a01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>5cb582dc-de6e-4ab7-adcf-54650a5e001a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>c853eb4d-148c-472a-98e8-09a31e86edde</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>error</value>
      <webElementGuid>05600337-a52e-4a41-883e-87a28777a525</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ou ov ow ox oy oz pa pb pc pd pe pf pg ph pi nk by pj</value>
      <webElementGuid>dec68a41-7c96-44bc-a3a6-ec79ecba7641</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>.*</value>
      <webElementGuid>992c5091-2d34-4662-b32b-1fb1b28e256f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c0b969fd-755c-431e-bfb9-fa484f9e2532</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[3]/div[@class=&quot;am bq an mi mj mk ml mm mn ag ah ig ai aj mo&quot;]/div[@class=&quot;mp mq mr ms mt mu&quot;]/div[@class=&quot;pw-susi-modal gm mv mw y cu mx my mz na nb nc&quot;]/div[@class=&quot;gm cx ae nd am ax kd ne nf ng nh&quot;]/div[@class=&quot;ni nj am bq cy an bp nk nl nm ng&quot;]/div[@class=&quot;ns y&quot;]/div[@class=&quot;am bq cy&quot;]/div[@class=&quot;ot nt y&quot;]/div[1]/div[@class=&quot;pk pf am bq cy nk&quot;]/div[@class=&quot;cu&quot;]/div[@class=&quot;x y&quot;]/p[@class=&quot;bv b ec eb ho&quot;]/input[@class=&quot;ou ov ow ox oy oz pa pb pc pd pe pf pg ph pi nk by pj&quot;]</value>
      <webElementGuid>b6c26e9b-e3e1-4d0d-9c6c-c465f424f7f5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='']</value>
      <webElementGuid>cd0c2589-daa6-4d1a-9592-d1f6ce1e8211</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>381e9bcc-77b2-4ded-a92f-0cbcacd41899</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text']</value>
      <webElementGuid>d68ad151-5484-4f24-b34f-5761a5ac31ce</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
