<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Sign In</name>
   <tag></tag>
   <elementGuidId>34e785c5-0966-4c92-ba78-3271039f837c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//header[@id='header']/div/div/div[3]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.button.flat.swap-icons</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>f6ea692a-ca9e-4c26-a191-8a1b9cee669c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/sessions/sign-in?next=%2F</value>
      <webElementGuid>f047778b-38a7-42e5-a748-524ebf71bf9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button flat swap-icons</value>
      <webElementGuid>84c7e290-0b6b-4476-a18c-506f8ee89248</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Sign In</value>
      <webElementGuid>056e8aab-c5cd-47ee-8eae-f6afcbabe4eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-balloon-pos</name>
      <type>Main</type>
      <value>left</value>
      <webElementGuid>1c6d8ac6-ef18-45f3-89f2-06416028787b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>  Sign In</value>
      <webElementGuid>61a32d4b-9d32-4d38-bef1-2310e150b06f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;header&quot;)/div[@class=&quot;container&quot;]/div[@class=&quot;wrap-app-header position-relative display-flex flex-items-center flex-content-between size-lg tablet:size-md&quot;]/div[@class=&quot;app-header-account display-flex flex-items-center tablet:margin-left-2xl&quot;]/a[@class=&quot;button flat swap-icons&quot;]</value>
      <webElementGuid>d632b8e8-e705-4f3f-b4a6-1192911c4b97</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//header[@id='header']/div/div/div[3]/a</value>
      <webElementGuid>ca97a6c0-1f9f-443e-a59b-89f4b174e11b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Blog'])[1]/following::a[1]</value>
      <webElementGuid>10b08c57-b64b-4879-b9df-1897d0dadf29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Support'])[1]/following::a[2]</value>
      <webElementGuid>872b6b44-8680-4687-8fce-9a150d9b0286</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/sessions/sign-in?next=%2F')]</value>
      <webElementGuid>ce764612-7fe6-4dd9-b6a4-5a496455f8f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/a</value>
      <webElementGuid>bfb7ac61-6c60-45e7-9fe8-d92d6d1888bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/sessions/sign-in?next=%2F' and (text() = '  Sign In' or . = '  Sign In')]</value>
      <webElementGuid>672e7178-17b7-4c36-a866-f81f14860011</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
