<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Tampilkan sandi</name>
   <tag></tag>
   <elementGuidId>9b1fcdf1-91c8-4481-a865-c85dd0cc1bc9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='selectioni1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#selectioni1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>fac0c7f4-2767-4217-b1ab-b7f7dcd4f575</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>selectioni1</value>
      <webElementGuid>9d99d0c9-5905-44f0-81bf-1f5850d77f60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>d3GVvd jGAaxb</value>
      <webElementGuid>ac80d807-79c5-48ad-9361-99878a846fdd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>jsname</name>
      <type>Main</type>
      <value>CeL6Qc</value>
      <webElementGuid>5b245711-a158-411c-9233-77479e2aa7d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Tampilkan sandi</value>
      <webElementGuid>a9a5c6b2-532e-4de1-8eee-7b0ebc838a76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;selectioni1&quot;)</value>
      <webElementGuid>61bd3388-154f-4759-ba92-4ca4bd602b6e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='selectioni1']</value>
      <webElementGuid>5973fcf6-2491-4bbd-83fd-8cc2df4a96d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='view_container']/div/div/div[2]/div/div/div/form/span/section/div/div/div[3]/div[3]/div/div/div/div/div[2]/div/div</value>
      <webElementGuid>babbfcfd-d029-4915-b4d4-3a1581f81710</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pilih sandi yang lebih kuat. Coba campuran huruf, angka, dan simbol.'])[1]/following::div[14]</value>
      <webElementGuid>d478e201-3705-4c85-99a6-957db1075040</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Gunakan alamat email saya saat ini sebagai gantinya'])[1]/following::div[41]</value>
      <webElementGuid>e99079cc-4b13-44e7-a822-ba8eed7dda7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Berikutnya'])[1]/preceding::div[7]</value>
      <webElementGuid>8e7d865a-7c3e-4897-9777-55d036878496</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Login saja'])[1]/preceding::div[13]</value>
      <webElementGuid>022214e9-09c1-4ee8-9f20-7f3decee259c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Tampilkan sandi']/parent::*</value>
      <webElementGuid>d0b0438b-1ca7-4698-a30c-8665cc32ff01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/div[2]/div/div</value>
      <webElementGuid>fbe087f3-45de-4eed-aed3-90323a93461c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'selectioni1' and (text() = 'Tampilkan sandi' or . = 'Tampilkan sandi')]</value>
      <webElementGuid>b85e71a8-d78a-4dc4-9e17-33687f83f7d7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
