<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i__eicon-close</name>
   <tag></tag>
   <elementGuidId>8136015b-eccd-4c90-a9dc-198a0b44669d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='elementor-popup-modal-18377']/div/div[4]/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.eicon-close</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>420f91c6-93d8-4a5e-8359-05470a9cd75c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>eicon-close</value>
      <webElementGuid>43363b5c-25e9-4014-8471-6eb5c5222653</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;elementor-popup-modal-18377&quot;)/div[@class=&quot;dialog-widget-content dialog-lightbox-widget-content animated&quot;]/div[@class=&quot;dialog-close-button dialog-lightbox-close-button&quot;]/i[@class=&quot;eicon-close&quot;]</value>
      <webElementGuid>c9c38452-c70f-4fdd-9d2d-97c41153507d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='elementor-popup-modal-18377']/div/div[4]/i</value>
      <webElementGuid>19bde1b0-c7e9-4bc4-8183-e366ec577c13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/i</value>
      <webElementGuid>23075d89-5f0a-4ad0-a178-08918ee48cac</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
