<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Daftar</name>
   <tag></tag>
   <elementGuidId>45ad547f-9ec3-416f-b84c-0f8dc83b9216</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='zeus-root']/div/main/div[2]/div[2]/div/form/button/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.css-1ksx3rf-unf-btn.eg8apji0 > span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>e7e362f2-797d-4e84-b036-bc273929a692</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Daftar</value>
      <webElementGuid>4032f12a-e678-4aa7-b748-a86238b084ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;zeus-root&quot;)/div[@class=&quot;css-3lpl5n&quot;]/main[@class=&quot;css-nuukba&quot;]/div[@class=&quot;css-1x0s3fz&quot;]/div[@class=&quot;right__container&quot;]/div[@class=&quot;css-173ke7b&quot;]/form[1]/button[@class=&quot;css-1ksx3rf-unf-btn eg8apji0&quot;]/span[1]</value>
      <webElementGuid>3e196f2a-ab1b-4f9b-9b8c-72115089805d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='zeus-root']/div/main/div[2]/div[2]/div/form/button/span</value>
      <webElementGuid>6e5dfdfa-53df-41dd-8834-c8a82f19127b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Phone Number or Email'])[1]/following::span[1]</value>
      <webElementGuid>bed8b0e7-9ace-4554-9ade-2f2a4d753fe8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='atau daftar dengan'])[1]/following::span[1]</value>
      <webElementGuid>ea1033c7-0a6c-4d53-b7da-6970df6e85b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dengan mendaftar, saya menyetujui'])[1]/preceding::span[1]</value>
      <webElementGuid>a59cc294-f477-4bcc-8eb7-905b30ce19c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Syarat dan Ketentuan'])[1]/preceding::span[1]</value>
      <webElementGuid>55b730f3-e03e-4eef-8184-0b3cb90eb509</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Daftar']/parent::*</value>
      <webElementGuid>965feaca-ebc0-4279-bc4d-4473bf11ed6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/button/span</value>
      <webElementGuid>70786c1b-2984-489b-9325-fa1c6603704e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Daftar' or . = 'Daftar')]</value>
      <webElementGuid>9009cd74-cf91-4f82-bca1-8a56bbe8d816</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
