<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_ihsankjamilgmail.comAdd voucherUpgradeSettingsLog out</name>
   <tag></tag>
   <elementGuidId>deef2bcd-8874-41c1-827b-21bee53c1f1f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div/div/div/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.ui.dropdown</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>db2c8c54-3600-4eb8-8694-3a936afd66a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>listbox</value>
      <webElementGuid>1947b06b-8731-4276-ad70-8b6cfbc4f5b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>0d332a4e-d7a2-4562-91e5-dc0db59c1adf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui dropdown</value>
      <webElementGuid>cdf77c14-3bbf-4d07-a183-38603ab7b19c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>f8f7ea97-4ff9-4bd7-ad77-2d76c539f847</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ihsankjamil@gmail.comAdd voucherUpgradeSettingsLog out</value>
      <webElementGuid>eb22ef8b-aa79-462c-bb11-167c17186884</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;_33T1-ZBLz7FQrNT-ZCfKte&quot;]/div[@class=&quot;_3noH-aE5rdGfZ-vqSixWLS&quot;]/div[@class=&quot;_1V4hZqsf6Tn_Uoxjno3LXT&quot;]/div[1]/div[@class=&quot;xvabTpfEZZTy4YhFJJyvf&quot;]/div[@class=&quot;_1-HEn3YHfECjM4qMyAyzAI&quot;]/div[@class=&quot;ui dropdown&quot;]</value>
      <webElementGuid>ace3a624-4336-40fa-ad56-718512ed647f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div/div/div/div</value>
      <webElementGuid>702fc458-b94c-45bf-937d-f339506d6ae6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Wallet Life'])[1]/following::div[3]</value>
      <webElementGuid>786a227e-e2b7-48a7-a593-066a863182f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div/div/div/div</value>
      <webElementGuid>b87ef4f2-c6d6-4c54-b942-2d59b6241f3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'ihsankjamil@gmail.comAdd voucherUpgradeSettingsLog out' or . = 'ihsankjamil@gmail.comAdd voucherUpgradeSettingsLog out')]</value>
      <webElementGuid>6191390f-14b1-431b-89f4-89ad8ae22e2d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
