<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Email_email</name>
   <tag></tag>
   <elementGuidId>193485bc-e00f-4257-a546-f7cb34e43961</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='email']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;email&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>823f0374-4bc6-4861-a1c7-8ae49665657d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>2b93087e-6c8b-4d88-92bd-28f60305e550</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>username</value>
      <webElementGuid>1f2a96e3-5e64-4a87-8d9d-db43c438494a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>8f3b7414-df81-43e5-804b-d6359a8e7a2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;_33T1-ZBLz7FQrNT-ZCfKte&quot;]/div[@class=&quot;_2Q6pBXLFUUUoruBimf55Sy&quot;]/div[@class=&quot;JCGbXzYpZ7WKcJyYY6VUb&quot;]/div[@class=&quot;_3gO9ST_7x00n9V1joHuS61&quot;]/div[@class=&quot;_2daPdGgWEXu9LICDdWxl8C&quot;]/div[@class=&quot;_14b-octJQUa4_KNZy0-7dn&quot;]/form[@class=&quot;ui error form&quot;]/div[@class=&quot;field&quot;]/div[@class=&quot;ui input&quot;]/input[1]</value>
      <webElementGuid>85384780-7a00-4b88-b5a2-403cd8e7e365</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='email']</value>
      <webElementGuid>efba937e-3afc-4bd1-85b1-76f2d260db7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[2]/div[3]/div/div/form/div/div/input</value>
      <webElementGuid>48bb6652-1bfe-4259-bfeb-ff0121e4b07c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>67e0461a-a8f4-45cc-9145-21e41c3552ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'email' and @type = 'email']</value>
      <webElementGuid>1a99e5db-d297-4317-a83e-d7defcbda316</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
