<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Sign In</name>
   <tag></tag>
   <elementGuidId>039141e2-d217-41a7-8026-6aa371a0a64c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='appMountPoint']/div/div/div/div/div/div/div/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.authLinks.redButton</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>0ecf8df1-ece9-4765-9126-387058789db1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/login</value>
      <webElementGuid>c035d74c-784f-47d0-821c-7b5cc35be639</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>authLinks redButton</value>
      <webElementGuid>9e7d056b-9760-44bd-b6ea-048dbfb784b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-uia</name>
      <type>Main</type>
      <value>header-login-link</value>
      <webElementGuid>564d5d2e-ae00-4348-aac2-ccfdb0e04f38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sign In</value>
      <webElementGuid>30f6729e-14f7-47fb-b700-5504331d4c1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;appMountPoint&quot;)/div[@class=&quot;basicLayout&quot;]/div[@class=&quot;netflix-sans-font-loaded&quot;]/div[@class=&quot;our-story-desktop-framework&quot;]/div[1]/div[@class=&quot;lang-selector-test our-story-container&quot;]/div[@class=&quot;our-story-header-wrapper&quot;]/div[@class=&quot;our-story-header&quot;]/a[@class=&quot;authLinks redButton&quot;]</value>
      <webElementGuid>9cbc3306-4af4-471a-8a8c-02c74895fb08</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='appMountPoint']/div/div/div/div/div/div/div/a</value>
      <webElementGuid>b5ab6263-13e1-49b6-aad4-7688c2877c5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Sign In')]</value>
      <webElementGuid>db0ffcbd-fefa-45af-a6c7-adc523a45325</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select Language'])[1]/following::a[1]</value>
      <webElementGuid>be56a5c5-8c66-4a9f-a46d-6f274d3ddade</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Netflix'])[1]/following::a[1]</value>
      <webElementGuid>47d12e52-64b4-4ebc-ae1e-152753f04eeb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Unlimited movies, TV shows, and more.'])[1]/preceding::a[1]</value>
      <webElementGuid>7d82386c-987f-4d5c-bfa3-520d02d8b824</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Watch anywhere. Cancel anytime.'])[1]/preceding::a[1]</value>
      <webElementGuid>34916ba7-2cf4-4b62-a1dc-a62d2e4f514c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Sign In']/parent::*</value>
      <webElementGuid>32de7877-ce82-4322-b8ec-708148289c2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/login')]</value>
      <webElementGuid>87562862-0091-4b15-8b78-9f1ae275fbe0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a</value>
      <webElementGuid>1fd7b081-e68c-4aec-8094-34c64a6687d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/login' and (text() = 'Sign In' or . = 'Sign In')]</value>
      <webElementGuid>d42a4ddf-d45d-44ae-acb7-ac7d27e66a38</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
